apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: web2
spec:
  template:
    spec:
      containers:
        - name: nginx2
          resources:
            limits:
              cpu: 50m
              memory: 6Mi
            requests:
              cpu: 10m
              memory: 5Mi
