apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: web2
  annotations:
    # This is a strategic merge patch, not a complete resource
    kustomize.config.k8s.io/behavior: merge
spec:
  template:
    spec:
      containers:
        - name: nginx2
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
