apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: web
spec:
  template:
    spec:
      containers:
        - name: nginx
          resources:
            limits:
              cpu: 50m
              memory: 4Mi
            requests:
              cpu: 10m
              memory: 3Mi
