apiVersion: apps/v1
kind: Deployment
metadata:
  name: http1
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: http1-container
        resources:
          limits:
            memory: 64Mi
          requests:
            memory: 32Mi
